"""users and products

Revision ID: 541a28437ebe
Revises: 1df1958b7a68
Create Date: 2019-04-15 11:29:20.819776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '541a28437ebe'
down_revision = '1df1958b7a68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_description', table_name='products')
    op.drop_index('ix_products_photo', table_name='products')
    op.drop_index('ix_products_price', table_name='products')
    op.drop_index('ix_products_title', table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('photo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('seller', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['seller'], ['users.id'], name='products_seller_fkey'),
    sa.PrimaryKeyConstraint('id', name='products_pkey')
    )
    op.create_index('ix_products_title', 'products', ['title'], unique=False)
    op.create_index('ix_products_price', 'products', ['price'], unique=False)
    op.create_index('ix_products_photo', 'products', ['photo'], unique=False)
    op.create_index('ix_products_description', 'products', ['description'], unique=False)
    # ### end Alembic commands ###
