version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql

