version: '3.1'

volumes:
  xcrafter.db:
    external: true

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - xcrafter.db:/var/lib/postgresql
    ports:
      - 127.0.0.1:5432:5432

